version: 2

general:
  branches:
    ignore:
      - gh-pages

machine:
  node:
    version: 8.6.0

general:
  artifacts:
    - packages/searchkit/coverage
    - packages/searchkit/lib
    - packages/searchkit/release
    - packages/searchkit-e2e-tests/cypress/video
    - packages/searchkit-e2e-tests/cypress/screenshots    

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: create test report folders
          command: "mkdir -p $CIRCLE_TEST_REPORTS/{jest,cypress}"
      - run:
          name: install lerna
          command: "npm install lerna -g"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install deps
          command: "yarn"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: "yarn build"

  test:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - (cd ./packages/searchkit && npm run test:ci)
      - (cd ./packages/searchkit-e2e-tests && npm run test:ci)
      - (cd ./packages/searchkit && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
      - cp packages/searchkit-e2e-tests/e2e-results.xml $CIRCLE_TEST_REPORTS/cypress
      - cp packages/searchkit/unit-results.xml $CIRCLE_TEST_REPORTS/jest

  # publish:
  #   docker:
  #     - image: circleci/<language>:<version TAG>
  #   steps:
  #     - checkout
  #     - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  #     - run: npm publish
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build

