version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/searchkit
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: "yarn"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - packages/searchkit/node_modules
            - packages/searchkit-e2e-docs/node_modules
            - packages/searchkit-docs/node_modules
      - run: "yarn build"
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/searchkit
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: "yarn"
      - run: "yarn workspace searchkit test:ci"
  features_test:
    docker:
      - image: cypress/base:8
    working_directory: ~/searchkit
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: "npm install -g yarn"
      - run: "yarn"
      - run: "yarn workspace searchkit-e2e-tests test:ci"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - features_test:
          requires:
            - build
        
