aliases:
  - &restore-monorepo-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      - dependencies-

  - &restore-searchkit-main-cache
    keys:
      - dependencies-searchkit-main-{{ checksum "packages/searchkit/package.json" }}
      - dependencies-searchkit-main-

  - &restore-repo-cache
    keys:
      - repo-{{ .Environment.CIRCLE_SHA1 }}

  - &save-monorepo-cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}

  - &save-searchkit-main-cache
    paths:
      - packages/searchkit/node_modules
    key: dependencies-searchkit-main-{{ checksum "packages/searchkit/package.json" }}

  - &restore-searchkit-cache
    keys:
      - dependencies-searchkit-{{ checksum "packages_checksum" }}
      - dependencies-searchkit-
  
  - &save-searchkit-cache
    paths:
      - packages/searchkit-e2e-tests/node_modules
    key: dependencies-searchkit-{{ checksum "packages_checksum" }}

  - &save-repo-cache
    paths:
      - ~/searchkit
      - ~/.cache
      - ~/.cache/Cypress
    key: repo-{{ .Environment.CIRCLE_SHA1 }}

defaults:
  - &job-defaults
      working_directory: ~/searchkit
      docker:
        - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *job-defaults
    steps:
      - checkout

      - attach_workspace:
          at: ~/searchkit
    
      - run:
          command: cat packages/searchkit-*/package.json > packages_checksum
          name: Creating checksum file for searchkit-* packages

      - restore_cache: *restore-monorepo-cache
      - restore_cache: *restore-searchkit-main-cache
      - restore_cache: *restore-searchkit-cache

      - run: yarn
      - run: yarn build

      - save_cache: *save-monorepo-cache
      - save_cache: *save-searchkit-main-cache
      - save_cache: *save-searchkit-cache

      - save_cache: *save-repo-cache

      - persist_to_workspace:
          root: .
          paths: .
  
  test:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/searchkit

      - checkout
      - run: yarn
      - run: yarn workspace searchkit test:ci

      - store_artifacts:
          path: coverage

  e2e:
    <<: *job-defaults
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/searchkit

      - run: yarn global add cypress
      - run: yarn workspace searchkit-e2e-tests test:ci

  deploy:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: ~/searchkit

      - checkout

      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - run: git config --global user.email phoey1@gmail.com
      - run: git config --global user.name "CircleCI"
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: PUBLISH_COMMIT=$(git log -1 --pretty=%B | cat | grep Publish) BRANCH=$CIRCLE_BRANCH npm run publish 

  # docs:
  #   <<: *job-defaults
  #   steps:
  #     - checkout

  #     - attach_workspace:
  #         at: ~/searchkit

  #     - run: |
  #         git diff --name-only HEAD~1 HEAD
  #         if [[ $(git diff --name-only HEAD~1 HEAD) =~ docs ]]; then
  #           # Build gitbook and move it to root directory
  #           yarn workspace run docs:build
  #           rm -rf ./docs
  #           mv ./_book/* ./

  #           git config user.name "CircleCI Docs"
  #           git config user.email "$DOCKER_EMAIL"

  #           git add .
  #           git commit -am 'Update Book'

  #           # Push generated files to gh-pages
  #           git push origin $CIRCLE_BRANCH:gh-pages --force
  #         fi

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          filters:
            branches:
              ignore: staging
      - e2e:
          requires:
            - build

      - docs:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
            - e2e
          filters:
            branches:
              only: 
                - staging
                - master
